spring.application.name=VotingSystem

server.port=8081

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=votingdb

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:chhavisharma0707@gmail.com}
spring.mail.password=${MAIL_PASSWORD:psrq cmdc ktno tgba}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${APP_BASE_URL:http://192.168.1.69:8081}
gemini.api.key=${GEMINI_API_KEY:}
